### ISSUE TITLE
编译之后 output 没有 那个libAR.a 。。。。。

### ISSUE THREAD

**Issue by ssj1314** [CharlyZhang/Vuforia-iOS-Lib#8]
大大 ，运行那个createARLib target，编译之后 output 没有 那个libAR.a : 新封装的静态库。。。 是更新了吗？
![03b2b063-b58f-4f8f-abec-c049de35918e](https://cloud.githubusercontent.com/assets/18111485/22635991/fd32318e-ec72-11e6-8838-3eb1909ba3a9.png)

**Comment by CharlyZhang** [comment]
你有没有将Vuforia的ios sdk 放到相应到文件夹下呢？像这样。
![image](https://cloud.githubusercontent.com/assets/7300993/22651472/1952a4fc-ecbe-11e6-9898-cd757e304af2.png)

**Comment by ssj1314** [comment]
我放了的，难道是sdk 我下错啦 ，但是就那一个好像。我重新下载试试
![c3efd8b9-0a20-49f4-a445-3fe7a9b58a6c](https://cloud.githubusercontent.com/assets/18111485/22673516/b8e3c292-ed15-11e6-854e-c40d3f9bdd5e.png)

**Comment by ssj1314** [comment]
解决啦，多谢作者无私帮助。

**Comment by CharlyZhang** [comment]
将你放vuforia sdk的文件夹名字改成Vuforia
